---
name: Release code

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - "*"

jobs:
  create-release:
    name: Create github release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - id: get-commit
        name: Get commit
        run: |
          COMMIT=$(git rev-list -n 1 "${{github.ref}}")
          echo "::set-output name=commit_ref::$COMMIT"
      - id: build-container
        name: Build Container
        run: |-
          docker buildx build -o type=oci,dest=image.tar .
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_commitish: ${{steps.get-commit.outputs.commit_ref}}
          files: |
            image.tar
